
  name: turingmachine
  version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Simple Turing machine # 79 char long summary
  description: |
    This program is a easy to use Turing machine.
    Fully programmable machine.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots
  
  apps:
    turingmachine:
      command: java -jar $SNAP/turingmachine-1.0.0/turingMachine.jar

  parts:
    turingmachine:
      # See 'snapcraft plugins'
      after: [desktop-glib-only]
      plugin: gradle
      source: .
      build: |
        export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
        gradle release -x test -x createGitTag
      install: |
        cp turingMachine.jar $SNAPCRAFT_PART_INSTALL/
      build-packages:
        - openjdk-8-jdk
  
